import Head from "next/head";
import Heros from "../../components/common/heros";
import Foooter from "../../components/foooter";
import Navigarion from "../../components/navigation";
import ProjectSection from "../../components/services/projectsection";
import HerosImg from "/public/backgrounds/main-slider-2-3.jpg";

const HerosText = "Services";

export default function Services(){

    return(
        <div>
            <Head>
                <title>Services</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/loader.png" />
            </Head>

            <main>
                <Navigarion />
                <Heros 
                        herosimag = {HerosImg}
                        text = {HerosText}
                />
                
                <ProjectSection />
            </main>

            <Foooter />
        </div>
    )
}