import Head from 'next/head';
import OurFermes from '../../components/aboutus/ourfermes';
import OverviewAbout from '../../components/aboutus/overviewabout';
import Heros from '../../components/common/heros';
import Foooter from '../../components/foooter';
import CatOn from '../../components/home-page/CrtOn';
import Navigarion from '../../components/navigation';
import HerosImg from "/public/backgrounds/page-header-bg.jpg";

const HerosText = "About US"

export default function AboutUs(){

    return(
        <div>
            <Head>
                <title>About US</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/loader.png" />
            </Head>

            <main>
                <Navigarion />
                <Heros 
                        herosimag = {HerosImg}
                        text = {HerosText}
                />
                <OverviewAbout />
                <OurFermes />
                <CatOn />
            </main>

            <Foooter />
        </div>
    )
}