import Head from "next/head";
import Heros from "../../components/common/heros";
import ContactFormSection from "../../components/contactus/contactformsection";
import MapAndContactIfo from "../../components/contactus/mapandcontactifo";
import Foooter from "../../components/foooter";
import Navigarion from "../../components/navigation";
import HerosImg from "/public/backgrounds/main-slider-1-3.jpg";

const HerosText = "Contact US";

export default function ContactUs(){

    return(
        <div>
            <Head>
                <title>Contact US</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/loader.png" />
            </Head>

            <main>
                <Navigarion />
                <Heros 
                        herosimag = {HerosImg}
                        text = {HerosText}
                />
                <MapAndContactIfo />
                <ContactFormSection />
            </main>

            <Foooter />
        </div>
    )
}